server:
  port: 8001

spring:
  application:
    name: delores-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-edu
#          uri: http://localhost:8008
          uri: lb://service-edu
          predicates:
            - Path=/edu/**

